Front end
uprm-inso-4117-2020-2021-s2/semester-project-team_5 pull request #11
Opened 2021-02-26 22:16 UTC by JoseBiescas

Added Sign-Up page and form for registration
Added link to Sign-Up page in Navbar
Added dummy action function for sign-up

2021-02-26 23:07 UTC, chris810 requested changes
I would put the different pages/views we are going to see in a folder named "views" so it would be src/views/signup/signup.js

2021-02-28 19:07 UTC, SamuelDiazBidot approved these changes

2021-03-01 13:31 UTC, JoseBiescas commented
Made changes requested by reviewer @chris810

2021-03-01 21:55 UTC, chris810 approved these changes
Great job this looks good to me!

2021-03-01 23:02 UTC, merged