Started implementing a package structure for the backend for easier…
uprm-inso-4117-2020-2021-s2/semester-project-team_5 pull request #2
Opened 2021-02-22 23:12 UTC by chris810

- Started implementing a package backend structure.

- Implemented basic_server with hello world output.

2021-02-23 17:30 UTC, JoseBiescas approved these changes

2021-02-23 17:34 UTC, JoseBiescas requested changes
Please add to the gitignore file hehe

*.pyc

2021-02-23 21:41 UTC, JoseBiescas approved these changes

2021-02-24 19:07 UTC, SamuelDiazBidot approved these changes

2021-02-26 00:42 UTC, merged